spring:
  application:
    name: spring-cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_01?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
